import { Software } from './types';

/**
 * The Gallery catalog. To add software: append an entry below, drop its logo in
 * `logos/` and reference the file name in `logo`. See `README.md` in this folder.
 */
export const gallery: Software[] = [
  {
    id: 'vorssaint',
    name: 'Vorssaint',
    tagline: 'Free and open-source macOS menu bar toolkit.',
    category: 'utilities',
    platforms: ['macos'],
    upstream: 'https://github.com/vorssaintapp/vorssaint-utils',
    website: 'https://vorssaint.com',
    license: 'GPL-3.0-or-later',
    logo: 'vorssaint.png',
    features: [
      'Per-app volume mixer and audio output routing',
      'System monitor: CPU, GPU, memory, temperature, fan and battery health',
      'App switcher with live thumbnails, window snapping and Dock previews',
      'Clipboard history, text snippets and a command bar',
      'Cleaner, uninstaller and Homebrew manager',
      'Install or uninstall each feature individually so unused ones never load',
    ],
    note: 'Replaces a pile of paid Mac utilities with one menu bar icon — no account, no telemetry, no subscription.',
  },
  {
    id: 'iina',
    name: 'IINA',
    tagline: 'The modern video player for macOS.',
    category: 'media',
    platforms: ['macos'],
    upstream: 'https://github.com/iina/iina',
    website: 'https://iina.io',
    license: 'GPL-3.0',
    logo: 'iina.png',
    features: [
      'Plays virtually every format — built on mpv and FFmpeg',
      'Native macOS design: dark mode, Picture-in-Picture, Touch Bar, Force Touch',
      'Playlist, chapter, subtitle and audio-track side panel',
      'Online subtitle search and automatic local subtitle loading',
      'Thumbnail preview on the seek bar and per-file playback resume',
      'JavaScript plugin system and customizable keyboard, mouse and trackpad controls',
    ],
    note: 'The one Mac video player that feels like a Mac app instead of a skinned mpv build.',
  },
  {
    id: 'insomnia',
    name: 'Insomnia',
    tagline: 'Open-source, cross-platform API client for GraphQL, REST, WebSockets, SSE and gRPC.',
    category: 'developer-tools',
    platforms: ['macos', 'windows', 'linux'],
    upstream: 'https://github.com/Kong/insomnia',
    website: 'https://insomnia.rest',
    license: 'Apache-2.0',
    logo: 'insomnia.svg',
    features: [
      'REST, GraphQL, gRPC, WebSocket and Server-Sent Events in one client',
      'Environments, variables and chained requests',
      'Collection runner for regression-testing an API',
      'Local, Git-backed or cloud storage per project',
      'OpenAPI import and design, plus code generation for many languages',
      '`inso` CLI to run the same collections and tests in CI',
    ],
    note: 'Lighter than Postman, and the Git-backed storage keeps request collections in the repo they belong to.',
  },
  {
    id: 'losslesscut',
    name: 'LosslessCut',
    tagline: 'The swiss army knife of lossless video/audio editing.',
    category: 'media',
    platforms: ['macos', 'windows', 'linux'],
    upstream: 'https://github.com/mifi/lossless-cut',
    website: 'https://losslesscut.app',
    license: 'GPL-2.0',
    logo: 'losslesscut.svg',
    features: [
      'Trim and cut video without re-encoding — no quality loss, near-instant export',
      'Merge or concatenate files, and split by segments or chapters',
      'Extract, remove or re-order individual audio, video and subtitle tracks',
      'Batch multiple segments and export them in one pass',
      'Repair broken or truncated recordings by remuxing them',
      'Export still frames and edit file metadata',
    ],
    note: 'The fastest way to chop the dead air off a long recording without waiting on an encode.',
  },
  {
    id: 'shutter-encoder',
    name: 'Shutter Encoder',
    tagline: 'A professional video compression tool accessible to all, mostly based on FFmpeg.',
    category: 'media',
    platforms: ['macos', 'windows', 'linux'],
    upstream: 'https://github.com/paulpacifico/shutter-encoder',
    website: 'https://www.shutterencoder.com',
    license: 'GPL-3.0',
    logo: 'shutter-encoder.png',
    features: [
      'Video, audio and image transcoding across H.264, H.265, ProRes, DNxHR, AV1 and VP9',
      'Lossless cut, trim, remux and stream extraction',
      'Batch queue with reusable presets and file-renaming rules',
      'Loudness analysis and normalization, LUTs, crop/scale/pad and watermarks',
      'Subtitle embedding, burn-in and editing',
      'Extras bundled in: yt-dlp downloads, RAW processing, MediaInfo and EXIF handling',
    ],
    note: 'A real GUI over FFmpeg that exposes the knobs professionals need instead of hiding them.',
  },
  {
    id: 'telegram',
    name: 'Telegram',
    tagline: 'Cloud-based messenger with open-source clients on every platform.',
    category: 'communication',
    platforms: ['macos', 'windows', 'linux', 'ios', 'android', 'web'],
    upstream: 'https://github.com/telegramdesktop/tdesktop',
    website: 'https://telegram.org',
    license: 'GPL-3.0 (clients)',
    logo: 'telegram.png',
    features: [
      'Messages sync across every device — desktop is a first-class client, not a phone mirror',
      'Groups up to 200,000 members, plus public channels and topics',
      'File sharing up to 2 GB per file (4 GB with Premium) with no format restrictions',
      'Bot and API platform, with an official CLI-friendly HTTP Bot API',
      'Native desktop apps for macOS, Windows and Linux built from source',
    ],
    note: 'Listed for the clients: all of them are open source and genuinely fast. The server side is proprietary, and only mobile "secret chats" are end-to-end encrypted.',
  },
  {
    id: 'zed',
    name: 'Zed',
    tagline: 'High-performance, multiplayer code editor from the creators of Atom and Tree-sitter.',
    category: 'developer-tools',
    platforms: ['macos', 'linux', 'windows'],
    upstream: 'https://github.com/zed-industries/zed',
    website: 'https://zed.dev',
    license: 'GPL-3.0 / Apache-2.0',
    logo: 'zed.png',
    features: [
      'Written in Rust on a GPU-accelerated UI framework — opens and types instantly',
      'Tree-sitter syntax parsing with built-in LSP support per language',
      'Real-time collaboration: shared buffers, channels and voice calls',
      'Integrated terminal, git diff view and project-wide search',
      'Agentic AI editing with your own model and API key',
      'Vim mode and an extension ecosystem',
    ],
    note: 'The only editor I have used where the latency is low enough to notice how slow everything else is.',
  },
];
