import { Software } from './types';

/**
 * The Gallery catalog. To add software: append an entry below, drop its logo in
 * `logos/` and reference the file name in `logo`. See `README.md` in this folder.
 */
export const gallery: Software[] = [
  {
    id: 'vorssaint',
    name: 'Vorssaint',
    tagline: 'Free and open-source macOS menu bar toolkit.',
    category: 'utilities',
    platforms: ['macos'],
    pricing: 'free',
    upstream: 'https://github.com/vorssaintapp/vorssaint-utils',
    website: 'https://vorssaint.com',
    logo: 'vorssaint.png',
  },
  {
    id: 'iina',
    name: 'IINA',
    tagline: 'The modern video player for macOS.',
    category: 'media',
    platforms: ['macos'],
    pricing: 'free',
    upstream: 'https://github.com/iina/iina',
    website: 'https://iina.io',
    logo: 'iina.png',
  },
  {
    id: 'insomnia',
    name: 'Insomnia',
    tagline: 'Open-source, cross-platform API client for GraphQL, REST, WebSockets, SSE and gRPC.',
    category: 'developer-tools',
    platforms: ['macos', 'windows', 'linux'],
    pricing: 'freemium',
    upstream: 'https://github.com/Kong/insomnia',
    website: 'https://insomnia.rest',
    logo: 'insomnia.svg',
  },
  {
    id: 'losslesscut',
    name: 'LosslessCut',
    tagline: 'The swiss army knife of lossless video/audio editing.',
    category: 'media',
    platforms: ['macos', 'windows', 'linux'],
    pricing: 'free',
    upstream: 'https://github.com/mifi/lossless-cut',
    website: 'https://losslesscut.app',
    logo: 'losslesscut.svg',
  },
  {
    id: 'shutter-encoder',
    name: 'Shutter Encoder',
    tagline: 'A professional video compression tool accessible to all, mostly based on FFmpeg.',
    category: 'media',
    platforms: ['macos', 'windows', 'linux'],
    pricing: 'free',
    upstream: 'https://github.com/paulpacifico/shutter-encoder',
    website: 'https://www.shutterencoder.com',
    logo: 'shutter-encoder.png',
  },
  {
    id: 'telegram',
    name: 'Telegram',
    tagline: 'Cloud-based messenger with open-source clients on every platform.',
    category: 'communication',
    platforms: ['macos', 'windows', 'linux', 'ios', 'android', 'web'],
    pricing: 'freemium',
    upstream: 'https://github.com/telegramdesktop/tdesktop',
    website: 'https://telegram.org',
    logo: 'telegram.png',
  },
  {
    id: 'zed',
    name: 'Zed',
    tagline: 'High-performance, multiplayer code editor from the creators of Atom and Tree-sitter.',
    category: 'developer-tools',
    platforms: ['macos', 'linux', 'windows'],
    pricing: 'free',
    upstream: 'https://github.com/zed-industries/zed',
    website: 'https://zed.dev',
    logo: 'zed.png',
  },
  {
    id: 'auto-subs',
    name: 'AutoSubs',
    tagline:
      'On-device subtitle generation that connects directly to DaVinci Resolve, Premiere, and After Effects.',
    category: 'media',
    platforms: ['macos', 'windows', 'linux'],
    pricing: 'free',
    upstream: 'https://github.com/tmoroney/auto-subs',
    website: 'https://tom-moroney.com/auto-subs/',
    logo: 'auto-subs.png',
  },
  {
    id: 'dinky',
    name: 'Dinky',
    tagline: 'A small macOS utility that compresses images, videos, and PDFs.',
    category: 'utilities',
    platforms: ['macos'],
    pricing: 'free',
    upstream: 'https://github.com/heyderekj/dinky',
    website: 'https://dinkyfiles.com',
    logo: 'dinky.png',
  },
  {
    id: 'pdfgear',
    name: 'PDFgear',
    tagline: 'Read, edit, convert, merge, and sign PDF files across devices, for completely free.',
    category: 'efficiency',
    platforms: ['macos', 'windows', 'ios', 'android', 'web'],
    pricing: 'free',
    upstream: 'https://www.pdfgear.com',
    logo: 'pdfgear.png',
  },
  {
    id: 'witr',
    name: 'witr',
    tagline:
      'Why is this running? Trace any process, port, container, or file back to what started it.',
    category: 'terminal',
    platforms: ['macos', 'windows', 'linux', 'cli'],
    pricing: 'free',
    upstream: 'https://github.com/pranshuparmar/witr',
    website: 'https://pranshuparmar.github.io/witr/',
  },
  {
    id: 'openlogi',
    name: 'OpenLogi',
    tagline:
      'A native, local-first alternative to Logitech Options+ — remap buttons, DPI, and SmartShift over HID++.',
    category: 'utilities',
    platforms: ['macos', 'windows', 'linux'],
    pricing: 'free',
    upstream: 'https://github.com/AprilNEA/OpenLogi',
    website: 'https://openlogi.org',
    logo: 'openlogi.png',
  },
  {
    id: 'screenpipe',
    name: 'Screenpipe',
    tagline:
      'Record your screen continuously and locally, and give the history to your agents as context.',
    category: 'utilities',
    platforms: ['macos', 'windows', 'linux'],
    pricing: 'paid',
    upstream: 'https://github.com/screenpipe/screenpipe',
    website: 'https://screenpipe.com',
    logo: 'screenpipe.png',
  },
  {
    id: 'cobalt',
    name: 'cobalt',
    tagline: 'Best way to save what you love — no ads, trackers or paywalls.',
    category: 'media',
    platforms: ['web'],
    pricing: 'free',
    upstream: 'https://github.com/imputnet/cobalt',
    website: 'https://cobalt.tools',
    logo: 'cobalt.png',
  },
  {
    id: 'vhs',
    name: 'VHS',
    tagline: 'Write terminal GIFs as code, for integration testing and demoing your CLI tools.',
    category: 'terminal',
    platforms: ['macos', 'windows', 'linux', 'cli'],
    pricing: 'free',
    upstream: 'https://github.com/charmbracelet/vhs',
  },
  {
    id: 'lemon-cleaner',
    name: 'Lemon Cleaner',
    tagline:
      "Tencent's macOS cleanup tool: tailored junk scans, duplicate files, similar photos and disk space analysis.",
    category: 'utilities',
    platforms: ['macos'],
    pricing: 'free',
    upstream: 'https://github.com/Tencent/lemon-cleaner',
    website: 'https://lemon.qq.com',
    logo: 'lemon-cleaner.png',
  },
  {
    id: 'reactive-resume',
    name: 'Reactive Resume',
    tagline:
      'A free and open-source resume builder that makes it easy to create, update, and share your resume.',
    category: 'efficiency',
    platforms: ['web'],
    pricing: 'free',
    upstream: 'https://github.com/AmruthPillai/Reactive-Resume',
    website: 'https://rxresu.me',
    logo: 'reactive-resume.png',
  },
];
